version: "3.8"

services:
  neo4j:
    container_name: neo4j
    image: neo4j:2025.10.1
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_server_directories_import=/import
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.algo.travelingSalesman
    volumes:
      - neo4j_data:/data
      - ./example_data:/import
volumes:
  neo4j_data:
