services:
  neo4j_api:
    container_name: neo4j_api
    pull_policy: never
    image: neo4j_api:latest
    build:
      context: .
      target: neo4j_api
    ports:
      - "8080:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSPHRASE=""
    depends_on:
      - neo4j
  neo4j:
    container_name: neo4j
    image: neo4j:2025.10.1
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_server_directories_import=/import
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc-extended", "apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.algo.dijkstra
      - NEO4J_dbms_allow__upgrade=true
      - EXTENSION_SCRIPT=/tmp/import_script.sh
    volumes:
      - neo4j_data:/data
      - ./import_data:/import
      - ./init/import_script.sh:/tmp/import_script.sh

volumes:
  neo4j_data:
    name: neo4j_data
