services:
  neo4j:
    container_name: neo4j
    image: neo4j:2025.10.1
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_server_directories_import=/import
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc-extended", "apoc", "graph-data-science"]
    volumes:
      - neo4j_data:/data
      - ./example_data:/import

volumes:
  neo4j_data:
    name: neo4j_data