services:
  ui:
    container_name: holiday-ui
    pull_policy: never
    image: holiday_internal_ui
    build:
      context: .
      target: ui
    ports:
      - 8501:8501
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_HEADLESS=true
      - API_URL=http://neo4j_api:8080
    depends_on:
      - neo4j_api
  neo4j_api:
    container_name: neo4j_api
    pull_policy: never
    image: neo4j_api:latest
    build:
      context: .
      target: neo4j_api
    ports:
      - "8080:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSPHRASE=""
      - LOG_LEVEL=INFO
    depends_on:
      - neo4j
  neo4j:
    container_name: neo4j
    image: neo4j:2025.10.1
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_server_directories_import=/import
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc-extended", "apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*,algo.*
      - NEO4J_dbms_allow__upgrade=true
      - EXTENSION_SCRIPT=/tmp/init/import_script.sh
    volumes:
      - neo4j_data:/data
      - ./import_data:/import
      - ./init:/tmp/init

volumes:
  neo4j_data:
    name: neo4j_data
